config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about',         to: 'static_pages#about',         as: 'about'
  get '/how_it_works',  to: 'static_pages#how_it_works',  as: 'how_it_works'
  get 'signup',   to: 'members#new',            as: 'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :members
  resources :account_activations, only: [:edit]
  resources :mechanics do
    resources :appointments, only: [:new, :create] do
      get :approve
      get :deny
      get :seller_approve
      get :seller_deny
    end
  end
  resources :admins, only: [:show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @form = EdmundsApi.new make: params[:make], model: params[:model], year: params[:year]
  end

  def help
  end

  def about
  end

  def how_it_works
    @account_items = [
                      "Enter your ZIP code along with the year, make, and model of the vehicle you’d like inspected.",
                      "Choose 'Find a Mechanic' and view your search results––we leave mechanic selection entirely up to you. Select your mechanic based on price, reviews, availability, and certifications.",
                      "Click 'Book an Appointment' on your mechanic’s profile page. Enter the vehicle seller’s contact information and the desired inspection time and location. Your inspection request will be directed both to the seller and to your preferred mechanic for approval.",
                      "Complete the payment page. We’ll put a hold on your payment until the inspection has been completed and the mechanic has generated a satisfactory report. You’ll only be charged for a complete, thorough job.",
                      "After mechanic and seller approval, inspectX quality assurance will approve your request to begin the process. The inspection will take place at the specified time and place, and the mechanic will forward the report to inspectX for approval. We will complete the hold on your payment and send you the reviewed, approved inspection report.",
                      "Armed with a thorough inspection report, you’ll be ready to make an informed decision about your used vehicle purchase."
                      ]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
- provide(:title, 'About')
%h1 About Us
%p inspectX simplifies your used car search. Our expert, user-reviewed mechanics work full-time in the automotive field and are capable of providing you with a thorough look at a vehicle’s cosmetic and mechanical condition before you buy. Our comprehensive 150-point inspection checklist ensures that every vehicle system is diligently examined. And our innovative pricing marketplace means that brand-specialized mechanics compete for your business.

%p Experience inspectX-certified peace of mind before your next purchase.

app/views/static_pages/help.html.haml
- provide(:title, 'Help')
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.haml

app/views/static_pages/home.html.haml
%h1 Test Api
%form
  %label Make 
  %input{type: 'text', name: 'make', value: params[:make]}
  %br
  %label Model 
  %input{type: 'text', name: 'model', value: params[:model]}
  %br
  %label Year 
  %input{type: 'text', name: 'year', value: params[:year]}
  %br

  %br
  %button Submit
  = link_to 'Clear', root_path
%ul
  - @form.response.each do |itm|
    %li 
      = itm

app/views/static_pages/how_it_works.html.haml
- provide(:title, 'Contact')

%h1 Streamlined. Expert. Thorough.

%p.center Finding a trustworthy, specialized mechanic for a pre-purchase inspection has never been easier.

.list
  .row
    .col-md-1
      .num
        1
    .col-md-11
      .cont
        = link_to 'Create', new_member_path
        and confirm an account.


- @account_items.each_with_index do |ai, i|
  .list
    .row
      .col-md-1
        .num
          = i + 2
      .col-md-11
        .cont
          = ai