config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about',         to: 'static_pages#about',         as: 'about'
  get '/how_it_works',  to: 'static_pages#how_it_works',  as: 'how_it_works'
  get 'signup',   to: 'members#new',            as: 'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :members
  resources :account_activations, only: [:edit]
  resources :mechanics do
    resources :appointments, only: [:new, :create] do
      get :approve
      get :deny
      get :seller_approve
      get :seller_deny
    end
  end
  resources :admins, only: [:show]
end

app/models/mechanic.rb
class Mechanic < User
  has_one :mechanic_profile
  has_one :address
  has_many :ratings
  has_many :appointments
  has_many :specialties

  accepts_nested_attributes_for :mechanic_profile, :address, :specialties

  delegate :bio, :school, :work, :languages, to: :mechanic_profile

  def send_activation_email
    UserMailer.mechanic_account_activation(self).deliver_now
  end

  def send_profile_update_email
    UserMailer.mech_profile_update(self).deliver_now
  end
end

app/controllers/mechanics_controller.rb
class MechanicsController < ApplicationController
  before_action :logged_in_user, only: [:index,:show, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :grab_params, only: [:index]

  def index
    @mechanics = search(Mechanic).paginate(page: params[:page])
  end

  def new
    @user = Mechanic.new
  end

  def create
    @user = Mechanic.new(mechanic_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = 'Please check your email to activate your account'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = Mechanic.find(params[:id])
    @appointments = @user.appointments
  end

  def edit
    @user.send_profile_update_email
    flash[:info] = 'Update request sent to admins'
    redirect_to mechanic_url(id: params[:id])
  end

protected

  def grab_params
    session[:make] = params[:make].try(:capitalize)
    session[:model] = params[:model]
    session[:year] = params[:year]
  end

  def search(mechanics)
    mechanics = mechanics.includes(:address, :mechanic_profile, :specialties).references(:specialties).where(addresses: {zip: params[:zip]})

    if mechanics.count > 20 && params[:make]
      mech = mechanics.where(specialties: {vehicle_make: params[:make].capitalize})
      if mech.count >= 5
        mechanics = mech
      end
    end

    # if mechanics.count > 20 && params[:model]
    #   mech = mechanics.where(specialties: {vehicle_model: params[:model].capitalize})
    #   if mech.count >= 5
    #     mechanics = mech
    #   end
    # end

    mechanics
  end

  def mechanic_params
    params.require(:mechanic).permit(:name, :email, :password, :password_confirmation,
                                      mechanic_profile_attributes: [:school, :work, :bio, :cost],
                                      address_attributes: [:street, :city, :state, :zip],
                                      specialties_attributes: [
                                        specialty_one: [:vehicle_make],
                                        specialty_two: [:vehicle_make]
                                        # specialty_one: [:vehicle_year, :vehicle_make, :vehicle_model],
                                        # specialty_two: [:vehicle_year, :vehicle_make, :vehicle_model]
                                        ])
  end
end

app/views/mechanics/_mechanic.html.haml
.row.mechanic__index--mechanic
  .col-md-2
    = gravatar_for mechanic, 'gravatar-lg'
    .mechanic__index--name
      = link_to mechanic.name, mechanic
  .col-md-8
    .mechanic__index--title
      Bio
    .mechanic__index--bio
      = mechanic.mechanic_profile.bio
    .row
      .col-md-10
        .mechanic__index--specialties
          Specialites:
        = mechanic.specialties.map {|spec| spec.vehicle_make + " " + spec.vehicle_model}.join(', ')
  .col-md-2.mechanic__price
    $ #{mechanic.mechanic_profile.cost} USD

app/views/mechanics/_mechanic_appointment.html.haml
%tr.clickable.accordian-toggle
  %td
    .appointment__table-button.collapsed(data-target='##{acc_base}-#{row_id}' data-toggle='collapse')
      .glyphicon.glyphicon-chevron-right.appointment__table-button--plus
  %td
    =appointment.member.try(:name)
  %td
    =appointment.start.try(:strftime, '%B %d, %Y at %H:%m %p')
  %td
    =appointment.vehicle_year
  %td
    =appointment.vehicle_make
  %td
    =appointment.vehicle_model
  - if show_actions
    %td
      %a.btn.btn-success.btn-circle(type='button' href='#{mechanic_appointment_approve_path(@user, appointment)}')
        %i.glyphicon.glyphicon-ok
      %a.btn.btn-danger.btn-circle(type='button' href='#{mechanic_appointment_deny_path(@user, appointment)}')
        %i.glyphicon.glyphicon-remove
%tr
  %td(colspan=7)
    .collapse(id='#{acc_base}-#{row_id}')
      - if type == 'pending'
        .alert.alert-warning
          = appointment.pending_status
      .row
        .col-md-3
          = gravatar_for(appointment.member)
          = appointment.member.name
        .col-md-9
          %p
            Seller Email: #{appointment.seller_email}
          %p
            Location: #{appointment.location}
          %p
            Notes:
          .well
            = appointment.notes

app/views/mechanics/_mechanic_appointments.html.haml
.panel.panel-primary
  .panel-heading
    = title
    - if appointments.count > 0 && show_badge
      %span.badge
        = appointments.count
  %table.table
    %thead
      %trow
        %th
        %th
          Member
        %th
          Time
        %th
          Year
        %th
          Make
        %th
          Model
        -if show_actions
          %th
            Approve?
      %tbody
        -appointments.each do |appointment|
          = render(partial: 'mechanic_appointment', locals: {row_id: appointment.id, appointment: appointment, acc_base: acc_base, show_actions: show_actions, type: type})

app/views/mechanics/edit.html.haml
- provide(:title, "Edit mechanic")
%h1 Update your profile
.row
  .col-md-4.col-md-offset-4
    = form_for(@user) do |f|
      = render(partial: 'shared/error_messages', locals: {object: @user})
      = f.label :name
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :password
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Save changes", class: "btn btn-primary"
    .gravatar.gravatar_edit
      = gravatar_for @user
      %a{:href => "http://gravatar.com/emails", :target => "_blank"} change

app/views/mechanics/index.html.haml
- content_for :footer do
  = javascript_include_tag 'car_query_on_ready.js'
  = javascript_include_tag 'car_query'

= render 'shared/mech_search_form'

- if params[:zip].present?
  %h2 Your Local Mechanics Serving #{params[:zip]}

- if @mechanics.present?
  .mechanics
    = render @mechanics
- elsif params[:zip]
  .panel.panel-danger
    .panel-heading
      .glyphicon.glyphicon-remove-sign
      Whoops!
    .panel-body
      It looks like your search returned no results. Try refining your search.
- else
  .panel.panel-warning
    .panel-heading
      .glyphicon.glyphicon-search
      So you're looking for a mechanic?
    .panel-body
      Use the above search form to find mechanics in your area
= will_paginate

app/views/mechanics/new.html.haml
- provide(:title, 'Sign up')
- content_for :footer do
 /= javascript_include_tag 'car_query_on_ready_mechanics.js'
 /= javascript_include_tag 'car_query'

%h1 Apply to be a Mechanic

= form_for(@user) do |f|
  .row
    .col-md-4.col-md-offset-4
      = render(partial: 'shared/error_messages', locals: {object: @user})
  .row
    .col-md-4.col-md-offset-2
      %h2 Account Information

      = f.label :name
      = f.text_field :name, class: 'form-control'

      = f.label :email
      = f.email_field :email, class: 'form-control'

      = f.label :password
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, "Confirmation"
      = f.password_field :password_confirmation, class: 'form-control'

      %h2 Address Information

      = f.fields_for :address_attributes do |ff|
        = ff.label :street
        = ff.text_field :street, class: 'form-control'

        = ff.label :city
        = ff.text_field :city, class: 'form-control'

        = ff.label :state
        = ff.text_field :state, class: 'form-control'

        = ff.label :zip
        = ff.text_field :zip, class: 'form-control'

    .col-md-4
      %h2 Profile Information

      = f.fields_for :mechanic_profile_attributes do |ff|
        = ff.label :school
        = ff.text_field :school, class: 'form-control'

        = ff.label :work
        = ff.text_field :work, class: 'form-control'

        = ff.label :bio
        = ff.text_area :bio, class: 'form-control'

        = ff.label :cost, 'Price for Service'
        = ff.number_field :cost, class: 'form-control'

      %h2 Auto Specialties
      %h5 Specialty 1

     




      = f.submit "Register", class: "btn btn-primary"

app/views/mechanics/show.html.haml
.row.mechanic__show--container
  .col-md-1
  .col-md-3
    = gravatar_for @user, 'mechanic__sidebar--image'
    .mechanic__sidebar--booking
    - if current_user.is_a? Member
      %a.btn.btn-primary.btn-md.mechanic__booking--button(href='#{new_mechanic_appointment_path(@user)}')
        .glyphicon.glyphicon-calendar
        Book an appointment

    .panel.panel-default.mechanic__about
      .panel-heading About Me
      .panel-body
        .mechanic__about--title School
        = @user.mechanic_profile.school
        .mechanic__about--title Work
        = @user.mechanic_profile.work

        - unless @user.mechanic_profile.try(:languages).blank?
          .mechanic__about--title Languages
          = @user.mechanic_profile.languages.join(', ')

  .col-md-7.mechanic__main--container
    .row
      .col-md-12
        .mechanic__heading
          = @user.name
        .mechanic__subheading--location
          #{@user.address.city}, #{@user.address.state}, United States · Member since #{@user.created_at.strftime('%B %Y')}
        .mechanic__subheading--certified
          .certified__icon.glyphicon.glyphicon-ok-circle
          .certified__text InspectX Certified
    .row
      .col-md-12
        .mechanic__bio
          = @user.mechanic_profile.bio
    .row
      .col-md-12
        .mechanic__index--specialties
          Specialties:
        = @user.specialties.map {|spec| spec.vehicle_make}.join(', ')
    - if current_user == @user
      .row
        .col-md-16
          = link_to 'Update my profile', edit_mechanic_path
          = render(partial: 'mechanic_appointments', locals: {appointments: @appointments.current, title: 'Current Appointments', acc_base: 'current_appointments', show_actions: false, show_badge: true, type: 'current'})
          = render(partial: 'mechanic_appointments', locals: {appointments: @appointments.pending, title: 'Pending Appointments', acc_base: 'pending_appointments', show_actions: true, show_badge: true, type: 'pending'})
          = render(partial: 'mechanic_appointments', locals: {appointments: @appointments.archived, title: 'Archived Appointments', acc_base: 'archived_appointments', show_actions: false, show_badge: false, type: 'archived'})

    .row
      .col-md-12
        .mechanic__reviews--container
          .mechanic__review--heading
            .mechanic__reviews--heading-title Reviews
            .mechanic__reviews--heading-count (#{@user.ratings.count})
          .mechanic__reviews--sub-heading
            Reviews from Customers
          - @user.ratings.each do |rating|
            .mechanic__review
              .row
                .col-md-2
                  .mechanic__review--image
                    = gravatar_for rating.member
                .col-md-8
                  .rating
                    - (1..(rating.rating)).each do |r|
                      %span★
                  = rating.description