config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about',         to: 'static_pages#about',         as: 'about'
  get '/how_it_works',  to: 'static_pages#how_it_works',  as: 'how_it_works'
  get 'signup',   to: 'members#new',            as: 'signup'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :members
  resources :account_activations, only: [:edit]
  resources :mechanics do
    resources :appointments, only: [:new, :create] do
      get :approve
      get :deny
      get :seller_approve
      get :seller_deny
    end
  end
  resources :admins, only: [:show]
end

app/views/layouts/_footer.html.haml
%footer.footer
  %nav
    %ul
      - unless logged_in?
        %li= link_to 'Mechanic? Apply here', new_mechanic_path
      %li= link_to 'About',   about_path

app/views/layouts/_navbar.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    %a#logo(href='#{root_path}')
      Inspect
      %sub.heading__x
        x
    -# =link_to 'inspectx', root_path, id: 'logo'
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          =link_to 'Home', root_path
          %li= link_to 'How it works', how_it_works_path
          %li= link_to 'Find a Mechanic', mechanics_path
        - if logged_in?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              - if current_user.is_a? Member
                %li= link_to "Settings", edit_member_path(current_user)
              - if current_user.is_a? Mechanic
                %li= link_to "Settings", edit_mechanic_path(current_user)
              %li.divider
              %li= link_to "Log out", logout_path, method: "delete"
        - else
          %li= link_to "Log in", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  %script{ :src => '//html5shiv.googlecode.com/svn/trunk/html5.js' }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic-ext", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/navbar'
    = yield(:no_container)

    .container.main-container
      - unless @no_container
        - flash.each do |message_type, message|
          %div{:class => "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?
      = yield(:footer)